config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_vona:
      branch: main
      repo: https://gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_vona
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_vona git:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-fuchsia-mayfly.sh
        container: qc.acc_sleazy-linen-boar
  QC.Doc:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_vona find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-maroon-molly.sh
        container: qc.doc_fuzzy-coral-quetzal
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_vona git:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-lime-chow.sh
        container: qc.doc_crabby-apricot-audemer
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_vona markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-purple-russel.sh
        container: qc.doc_silly-ecru-kangaroo
  QC.Lic:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_vona licensee:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-saffron-spoonbill.sh
        container: qc.lic_sickly-cardinal-dalmatian
  QC.Sec:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_vona bandit:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-green-whale.sh
        container: qc.sec_craggy-pink-ant
  QC.Sty:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_vona flake8:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-vermilion-chihuahua.sh
        container: qc.sty_surly-smalt-octopus
  QC.Uni:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_vona pytest:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-aquamarine-bobcat.sh
        container: qc.uni_bluesy-bistre-gopher
  QC.Ver:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_vona get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-platinum-neanderthal.sh
        container: qc.ver_woozy-apricot-zonkey
timeout: 5400
